name: Deploy to Steamship

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  deploy:
    name: Deploy to Steamship
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Deploy to Steamship
        uses: steamship-core/deploy-to-steamship@master
        with:
          steamship_key: ${{ secrets.STEAMSHIP_KEY }}